# Install pre-commit hooks via
# pre-commit install

repos:
  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: "0.4.0"  # the revision or tag to clone at
    hooks:
      - id: sync_with_poetry
        args: ["--all"]  # optional args
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files", "--skip", "__init__.py"]
        files: ^dodiscover/
  - repo: https://github.com/PyCQA/flake8
    rev: "6.0.0"
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.971"
    hooks:
      - id: mypy
        name: mypy (dodiscover)
        args: ["--config-file", "pyproject.toml"]
        files: ^dodiscover/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.971"
    hooks:
      - id: mypy
        name: mypy (tests)
        args: ["--config-file", "pyproject.toml"]
        files: ^tests/
